Application_RH/Models/CandidatoViewModel.cs
namespace Application_RH.Models
{
    public class CandidatoViewModel
    {
        public CandidatoViewModel()
        {
            Vagas = new List<VagaModel>();
            Tecnologias = new List<TecnologiaModel>();
        }
        public int Id { get; set; }
        public string? Nome { get; set; }
        public string? Contato { get; set; }
        public string NomeVaga { get; set; }
        public string Vaga { get; set; }
        public List<VagaModel>? Vagas { get; set; }
        public List<TecnologiaModel>? Tecnologias { get; set; }
        public List<string> StringTecnologias { get; set; }
    }
}

Application_RH/Controllers/CandidatoController.cs
using Application_RH.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace AppForRHTest.Controllers
{
    public class CandidatoController : Controller
    {
        private readonly string ENDPOINT = "https://localhost:7245/api/Candidato";
        private readonly HttpClient httpClient = null;
        public CandidatoController()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri(ENDPOINT); 
        }

        public async Task<IActionResult> Visualizar()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                List<CandidatoModel> candidatos = null;

                HttpResponseMessage response = await httpClient.GetAsync(httpClient.BaseAddress);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    candidatos = JsonConvert.DeserializeObject<List<CandidatoModel>>(content);
                    
                    foreach (CandidatoModel candidato in candidatos)
                    {
                        string newTecnologias = "";
                        string[] arrayTecs = candidato.Tecnologias.Split(",");
                        bool primeiraRepeticao = true;
                        foreach (string t in arrayTecs)
                        {
                            string[] strings = t.Trim().Split(" ");
                            if (primeiraRepeticao) {
                                newTecnologias += strings[0];
                                primeiraRepeticao = false;
                                continue;
                            }
                            newTecnologias += ", " + strings[0];
                        }
                        candidato.Tecnologias = newTecnologias;
                    }
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(candidatos);
            }
            catch (Exception ex) 
            {
                return View(ex);
            }
        }

        public async Task<IActionResult> Criar()
        {
            try
            {
                List<TecnologiaModel> tecnologias = null;
                List<VagaModel> vagas = null;
                CandidatoViewModel fmtCandidato = new CandidatoViewModel();

                HttpResponseMessage tecResponse = await httpClient.GetAsync("https://localhost:7245/api/Tecnologia");
                HttpResponseMessage vagasResponse = await httpClient.GetAsync("https://localhost:7245/api/Vaga");

                if (tecResponse.IsSuccessStatusCode && vagasResponse.IsSuccessStatusCode)
                {
                    string tecContent = await tecResponse.Content.ReadAsStringAsync();
                    string vagasContent = await vagasResponse.Content.ReadAsStringAsync();

                    tecnologias = JsonConvert.DeserializeObject<List<TecnologiaModel>>(tecContent);
                    vagas = JsonConvert.DeserializeObject<List<VagaModel>>(vagasContent);

                    foreach (VagaModel vaga in vagas)
                    {
                        fmtCandidato.Vagas.Add(vaga);
                    }

                    foreach (TecnologiaModel tecnologia in tecnologias){
                        fmtCandidato.Tecnologias.Add(tecnologia);
                    }
                    
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                fmtCandidato.StringTecnologias = new List<string>();
                return View(fmtCandidato);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Criar(CandidatoViewModel candidato, string[] StringTecnologias)
        {
            try
            {
                string allTecnologias = StringTecnologias[0];
                foreach(string tecnologia in StringTecnologias)
                {
                    if (tecnologia != StringTecnologias[0]) allTecnologias += ", " + tecnologia;
                }
                string[] cVaga = candidato.Vaga.Split("|");
                CandidatoModel newCandidato = new CandidatoModel();

                newCandidato.Nome = candidato.Nome;
                newCandidato.Contato = candidato.Contato;
                newCandidato.NomeVaga = cVaga[0];
                newCandidato.IdVaga = int.Parse(cVaga[1]);
                newCandidato.Tecnologias = allTecnologias;
                
                var CandidatoFormatado = JsonConvert.SerializeObject(newCandidato);

                var data = new StringContent(CandidatoFormatado, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await httpClient.PostAsync(ENDPOINT, data);
                Console.WriteLine(data);
                if (!response.IsSuccessStatusCode)
                {
                    ModelState.AddModelError(null, "Erro ao processar a solicitação");
                }
                
                return RedirectToAction("TecnologiaVaga");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> TecnologiaVaga(int id)
        {
            return View();
        }


        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                CandidatoModel candidato = null;
                HttpResponseMessage response = await httpClient.GetAsync(ENDPOINT+"/"+id);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    candidato = JsonConvert.DeserializeObject<CandidatoModel>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(candidato);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Editar(CandidatoModel candidato)
        {
            try
            {
                var CandidatoFormatado = JsonConvert.SerializeObject(candidato, Formatting.Indented);

                var data = new StringContent(CandidatoFormatado, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await httpClient.PutAsync(new Uri(ENDPOINT+"/atualizarCandidato/"+candidato.Id), data);

                if (!response.IsSuccessStatusCode)
                {
                    ModelState.AddModelError(null, "Erro ao processar a solicitação");
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> Apagar(int id)
        {
            try
            {
                Console.WriteLine("teste"+id);
                HttpResponseMessage response = await httpClient.DeleteAsync(ENDPOINT + "/deletarCandidato/" + id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> ApagarConfirmacao(int id)
        {
            try
            {
                CandidatoModel candidato = null;
                HttpResponseMessage response = await httpClient.GetAsync(ENDPOINT + "/" + id);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    candidato = JsonConvert.DeserializeObject<CandidatoModel>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(candidato);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }
    }
}

Application_RH/Views/Candidato/ApagarConfirmacao.cshtml
@model CandidatoModel
@{
    ViewData["Title"] = "Confirmacao apagar candidato";
}

<div class="text-center">

    <h3 class="display-4">Deseja realmente apagar o candidato @Model.Nome?</h3>

</div>

<a role="button" class="btn btn-danger btn-block" asp-controller="Candidato" asp-route-id="@Model.Id" asp-action="Apagar"> Confirmar exclusão </a>
<a role="button" class="btn btn-primary btn-block" asp-controller="Candidato" asp-action="Index">Cancelar</a>

Application_RH/Views/Candidato/Criar.cshtml
@model CandidatoViewModel

@{
    ViewData["Title"] = "Cadastrar candidato";
}

<div class="text-center">

    <h3 class="display-4">Cadastrar Candidato</h3>

</div>

<form id="form" class="mx-auto w-75" asp-controller="Candidato" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" id="name" placeholder="Digite o nome do candidato">
    </div>
    <div class="form-group">
        <label for="contact">Contato</label>
        <input type="text" asp-for="Contato" class="form-control" id="contact" placeholder="Digite o número do candidato">
    </div>
    <hr />
    <p class="h3">Vagas disponíveis: </p>
    @if (Model != null && Model.Vagas.Any())
    {
        @foreach (var item in Model.Vagas)
        {
            <input class="form-check-input" id="@item.Nome" type="radio" asp-for="Vaga" value="@item.Nome|@item.Id" />
            <label class="form-check-label" for="@item.Nome">@item.Nome</label>
        }
    }
    <hr />
    <p class="h3">Tecnologias da empresa: </p>
    @if (Model != null && Model.Tecnologias.Any())
    {
        @foreach (var item in Model.Tecnologias)
        {
            <div>
                <input class="form-check-input" id="@item.Nome" name="StringTecnologias" type="checkbox" value="@item.Nome @item.Id">
                <label class="form-check-label" for="@item.Nome">
                    @item.Nome
                </label>
            </div>
        }
    }
    <div class="d-flex justify-content-around p-3">
        <button type="submit" class="btn btn-primary w-25">Criar</button>
        <a role="button" class="btn btn-secondary w-25" asp-controller="Candidato" asp-action="Index">Voltar</a>
    </div>

</form>

Application_RH/Views/Candidato/Editar.cshtml
@model CandidatoModel

@{
    ViewData["Title"] = "Editar candidato";
}

<div class="text-center">

    <h3 class="display-4">Editar Candidato @Model.Nome?</h3>

</div>

<form id="form" asp-controller="Candidato" asp-action="Editar" method="post">
    <input type="text" asp-for="Id" hidden/>
    <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" id="name" placeholder="Digite o nome do candidato">
    </div>
    <div class="form-group">
        <label for="contact">Contato</label>
        <input type="text" asp-for="Contato" class="form-control" id="contact" placeholder="Digite o número do candidato">
    </div>
    <button type="submit" class="btn btn-primary w-25">Editar</button>
    <a role="button" class="btn btn-secondary w-25" asp-controller="Candidato" asp-action="Index">Voltar</a>
</form>

Application_RH/Views/Candidato/Index.cshtml
@model List<CandidatoModel>

@{
    ViewData["Title"] = "Candidatos";
}

<div class="text-center">
    <h3 class="display-4">Listagem de Candidatos</h3>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Contato</th>
                <th scope="col">Vaga</th>
                <th scope="col">Tecnologias</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (CandidatoModel item in Model)
                {
                    <tr>
                        <th scope="row"> @item.Id </th>
                        <td> @item.Nome </td>
                        <td> @item.Contato </td>
                        <td> @item.NomeVaga </td>
                        <td> @item.Tecnologias </td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@item.Id" asp-controller="Candidato" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-secondary" asp-route-id="@item.Id" asp-controller="Candidato" asp-action="Visualizar">Visualizar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@item.Id"  asp-controller="Candidato" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        <a role="button" class="btn btn-primary" asp-controller="Candidato" asp-action="Criar"> Novo candidato </a>
    </div>
</div>

Application_RH/Views/Candidato/Visualizar.cshtml
@model CandidatoViewModel

@{
    ViewData["Title"] = "Candidato";
}

<div class="text-center">
    <h3 class="display-4">Candidato @Model.Nome</h3>

    <p>Contato: @Model.Contato</p>
    <p>Concorrendo à Vaga: @Model.Vaga</p>
    <p>Tecnologias conhecidas: @Model.Tecnologias</p>


    <div class="d-flex justify-content-center">
        <a role="button" class="btn btn-primary" asp-controller="Candidato" asp-action="Index"> Voltar Para Listagem </a>
    </div>
</div>