Application_RH/Controllers/VagaController.cs
using Application_RH.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppForRHTest.Controllers
{
    public class VagaController : Controller
    {
        private readonly string ENDPOINT = "https://localhost:7245/api/Vaga";
        private readonly HttpClient httpClient = null;
        public VagaController()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri(ENDPOINT);
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                List<VagaModel> vagas = null;

                HttpResponseMessage response = await httpClient.GetAsync(httpClient.BaseAddress);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    vagas = JsonConvert.DeserializeObject<List<VagaModel>>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(vagas);
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Criar(VagaModel vaga)
        {
            try
            {
                var vagaFormatado = JsonConvert.SerializeObject(vaga);

                var data = new StringContent(vagaFormatado, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await httpClient.PostAsync(ENDPOINT, data);

                if (!response.IsSuccessStatusCode)
                {
                    ModelState.AddModelError(null, "Erro ao processar a solicitação");
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                VagaModel vaga = null;
                HttpResponseMessage response = await httpClient.GetAsync(ENDPOINT + "/" + id);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    vaga = JsonConvert.DeserializeObject<VagaModel>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(vaga);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Editar(VagaModel vaga)
        {
            try
            {
                var vagaFormatado = JsonConvert.SerializeObject(vaga, Formatting.Indented);

                var data = new StringContent(vagaFormatado, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await httpClient.PutAsync(new Uri(ENDPOINT + "/atualizarVaga/" + vaga.Id), data);

                if (!response.IsSuccessStatusCode)
                {
                    ModelState.AddModelError(null, "Erro ao processar a solicitação");
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> Apagar(int id)
        {
            try
            {
                Console.WriteLine("teste" + id);
                HttpResponseMessage response = await httpClient.DeleteAsync(ENDPOINT + "/deletarVaga/" + id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> ApagarConfirmacao(int id)
        {
            try
            {
                VagaModel vaga = null;
                HttpResponseMessage response = await httpClient.GetAsync(ENDPOINT + "/" + id);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    vaga = JsonConvert.DeserializeObject<VagaModel>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(vaga);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }
    }
}

Application_RH/Views/Vaga/ApagarConfirmacao.cshtml
@model VagaModel

@{
    ViewData["Title"] = "Confirmacao deletar vaga";
}

<div class="text-center">

    <h3 class="display-4">Deseja realmente apagar a tecnologia:</h3>
    <h3 class="display-4">"@Model.Nome"?</h3>

</div>
<div class="d-flex justify-content-around w-50 mx-auto">
    <a role="button" class="btn btn-primary" asp-controller="Vaga" asp-action="Index"> Cancelar</a>
    <a role="button" class="btn btn-danger" asp-controller="Vaga" asp-route-id="@Model.Id" asp-action="Apagar"> Confirmar exclusão </a>
</div>

Application_RH/Views/Vaga/Criar.cshtml
@model VagaModel

@{
    ViewData["Title"] = "Criar vaga";
}

<div class="text-center">

    <h3 class="display-4">Criar Vaga</h3>

</div>

<form id="form" asp-controller="Vaga" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" id="name" placeholder="Digite o nome da Vaga">
    </div>
    <div class="d-flex justify-content-around p-3">
        <button type="submit" class="btn btn-primary w-25">Criar</button>
        <a role="button" class="btn btn-secondary w-25" asp-controller="Vaga" asp-action="Index">Voltar</a>
    </div>
</form>

Application_RH/Views/Vaga/Editar.cshtml
@model VagaModel

@{
    ViewData["Title"] = "Editar vaga";
}

<div class="text-center">

    <h3 class="display-4">Editar Vaga "@Model.Nome"?</h3>

</div>

<form id="form" asp-controller="Vaga" class="mx-auto w-75" asp-action="Editar" method="post">
    <input type="text" asp-for="Id" hidden />
    <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" id="name" value="" placeholder="@Model.Nome">
    </div>
    <div class="d-flex justify-content-around p-3">
        <button type="submit" class="btn btn-primary w-25">Editar</button>
        <a role="button" class="btn btn-secondary w-25" asp-controller="Vaga" asp-action="Index">Voltar</a>
    </div>
</form>

Application_RH/Views/Vaga/Index.cshtml
@model List<VagaModel>

@{
    ViewData["Title"] = "Vagas";
}

<div class="text-center">
    <h3 class="display-4">Listagem de Vagas</h3>

    <table class="table table-striped w-50 mx-auto">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Vaga</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (VagaModel item in Model)
                {
                    <tr>
                        <th scope="row"> @item.Id </th>
                        <td> @item.Nome </td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@item.Id" asp-controller="Vaga" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@item.Id" asp-controller="Vaga" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        <a role="button" class="btn btn-primary" asp-controller="Vaga" asp-action="Criar"> CADASTRAR NOVA VAGA </a>
    </div>
</div>