Application_RH/Models/TecnologiaViewModel.cs
namespace Application_RH.Models
{
    public class TecnologiaViewModel
    {
        public TecnologiaViewModel()
        {
            Vagas = new List<VagaModel>();
        }
        public int Id { get; set; }
        public string? Nome { get; set; }
        public List<VagaModel>? Vagas { get; set; }
        public string[] pesoTecs { get; set; }

    }
}

Application_RH/Controllers/TecnologiaController.cs
using Application_RH.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppForRHTest.Controllers
{
    public class TecnologiaController : Controller
    {
        private readonly string ENDPOINT = "https://localhost:7245/api/Tecnologia";
        private readonly HttpClient httpClient = null;
        public TecnologiaController()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri(ENDPOINT);
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                List<TecnologiaModel> tecnologias = null;

                HttpResponseMessage response = await httpClient.GetAsync(httpClient.BaseAddress);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    tecnologias = JsonConvert.DeserializeObject<List<TecnologiaModel>>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(tecnologias);
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }

        public async Task<IActionResult> TecnologiaVaga(int id)
        {
            try
            {
                List<VagaModel> vagas = null;
                TecnologiaViewModel fmtTecnologia = new TecnologiaViewModel();
                TecnologiaModel tecModel = null;

                HttpResponseMessage vagasResponse = await httpClient.GetAsync("https://localhost:7245/api/Vaga");
                HttpResponseMessage tecResponse = await httpClient.GetAsync(ENDPOINT + "/" + id);

                if (vagasResponse.IsSuccessStatusCode)
                {
                    string vagasContent = await vagasResponse.Content.ReadAsStringAsync();
                    string tecContent = await tecResponse.Content.ReadAsStringAsync(); 

                    vagas = JsonConvert.DeserializeObject<List<VagaModel>>(vagasContent);
                    tecModel = JsonConvert.DeserializeObject<TecnologiaModel>(tecContent);
                    Console.WriteLine(tecModel);
                    fmtTecnologia.Id = tecModel.Id;
                    fmtTecnologia.Nome = tecModel.Nome;
                    
                    foreach (VagaModel vaga in vagas)
                    {
                        fmtTecnologia.Vagas.Add(vaga);
                    }

                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");
                
                return View(fmtTecnologia);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Criar(TecnologiaModel tecnologia)
        {
            try
            {
                var TecnologiaFormatado = JsonConvert.SerializeObject(tecnologia);
                TecnologiaViewModel cTec = null;
                var data = new StringContent(TecnologiaFormatado, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await httpClient.PostAsync(ENDPOINT, data);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    cTec = JsonConvert.DeserializeObject<TecnologiaViewModel>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");
                return RedirectToAction("TecnologiaVaga", new { id = cTec.Id.ToString() });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                TecnologiaModel tecnologia = null;
                HttpResponseMessage response = await httpClient.GetAsync(ENDPOINT + "/" + id);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    tecnologia = JsonConvert.DeserializeObject<TecnologiaModel>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(tecnologia);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Editar(TecnologiaModel tecnologia)
        {
            try
            {
                var tecnologiaFormatado = JsonConvert.SerializeObject(tecnologia, Formatting.Indented);

                var data = new StringContent(tecnologiaFormatado, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await httpClient.PutAsync(new Uri(ENDPOINT + "/atualizarTecnologia/" + tecnologia.Id), data);

                if (!response.IsSuccessStatusCode)
                {
                    ModelState.AddModelError(null, "Erro ao processar a solicitação");
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> AtualizarPeso(string[] pesoTecs)
        {
            try
            {
                foreach(string s in pesoTecs)
                {
                    TecnologiaVagaModel newTecVaga = new TecnologiaVagaModel();
                    string[] formatedString = s.Split(" ");
                    newTecVaga.IdVaga = int.Parse(formatedString[0]);
                    newTecVaga.IdTec = int.Parse(formatedString[1]);
                    newTecVaga.peso = int.Parse(formatedString[2]);
                    var pesoFormatado = JsonConvert.SerializeObject(newTecVaga, Formatting.Indented);
                    var data = new StringContent(pesoFormatado, Encoding.UTF8, "application/json");
                    HttpResponseMessage response = await httpClient.PostAsync(new Uri("https://localhost:7245/api/TecnologiaVaga"), data);

                    if (!response.IsSuccessStatusCode)
                    {
                        ModelState.AddModelError(null, "Erro ao processar a solicitação");
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }

        public async Task<IActionResult> Apagar(int id)
        {
            try
            {
                List<TecnologiaVagaModel> tecnologias = null;
                HttpResponseMessage response = await httpClient.DeleteAsync(ENDPOINT + "/deletarTecnologia/" + id);
                HttpResponseMessage response2 = await httpClient.DeleteAsync("https://localhost:7245/api/TecnologiaVaga/deletarTecnologiaVaga/" + id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> ApagarConfirmacao(int id)
        {
            try
            {
                TecnologiaModel tecnologia = null;
                HttpResponseMessage response = await httpClient.GetAsync(ENDPOINT + "/" + id);

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    tecnologia = JsonConvert.DeserializeObject<TecnologiaModel>(content);
                }
                else ModelState.AddModelError(null, "Erro ao processar a solicitação");

                return View(tecnologia);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View();
            }
        }
    }
}

Application_RH/Views/Tecnologia/ApagarConfirmacao.cshtml
@model TecnologiaModel

@{
    ViewData["Title"] = "Confirmacao apagar tecnologia";
}

<div class="text-center">

    <h3 class="display-4">Deseja realmente apagar a tecnologia:</h3>
    <h3 class="display-4">"@Model.Nome"?</h3>

</div>

<div class="d-flex justify-content-around w-50 mx-auto">
    <a role="button" class="btn btn-primary" asp-controller="Tecnologia" asp-action="Index"> Cancelar</a>
    <a role="button" class="btn btn-danger" asp-controller="Tecnologia" asp-route-id="@Model.Id" asp-action="Apagar"> Confirmar exclusão </a>
</div>

Application_RH/Views/Tecnologia/Criar.cshtml
@model TecnologiaModel

@{
    ViewData["Title"] = "Criar tecnologia";
}

<div class="text-center">

    <h3 class="display-4">Criar Tecnologia</h3>

</div>

<form id="form" class="mx-auto w-75" asp-controller="Tecnologia" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" id="name" placeholder="Digite o nome da Tecnologia">
    </div>
    <div class="d-flex justify-content-around p-3">
        <button type="submit" class="btn btn-primary w-25">Próximo</button>
        <a role="button" class="btn btn-secondary w-25" asp-controller="Tecnologia" asp-action="TecnologiaVaga">Voltar</a>
    </div>
</form>

Application_RH/Views/Tecnologia/Editar.cshtml
@model TecnologiaModel

@{
    ViewData["Title"] = "Editar tecnologia";
}

<div class="text-center">

    <h3 class="display-4">Editar Tecnologia @Model.Nome?</h3>

</div>

<form id="form" class="mx-auto w-75" asp-controller="Tecnologia" asp-action="Editar" method="post">
    <input type="text" asp-for="Id" hidden />
    <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" asp-for="Nome" value="" class="form-control" id="name" placeholder="@Model.Nome">
    </div>
    <div class="d-flex justify-content-around p-3">
        <button type="submit" class="btn btn-primary w-25">Editar</button>
        <a role="button" class="btn btn-secondary w-25" asp-controller="Tecnologia" asp-action="Index">Voltar</a>
    </div>
</form>

Application_RH/Views/Tecnologia/Index.cshtml
@model List<TecnologiaModel>

@{
    ViewData["Title"] = "Candidatos";
}

<div class="text-center">

    <br />

    <h3 class="display-4">Listagem de Tecnologias</h3>

    <table class="table table-striped mx-auto w-50">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Tecnologia</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (TecnologiaModel item in Model)
                {
                    <tr>
                        <th scope="row"> @item.Id </th>
                        <td> @item.Nome </td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@item.Id" asp-controller="Tecnologia" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@item.Id" asp-controller="Tecnologia" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        <a role="button" class="btn btn-primary" asp-controller="Tecnologia" asp-action="Criar"> CADASTRAR TECNOLOGIA </a>
    </div>
</div>

Application_RH/Views/Tecnologia/TecnologiaVaga.cshtml
@model TecnologiaViewModel

@{
    ViewData["Title"] = "Tecnologia - Vaga";
}

<div class="text-center">
    <h3 class="display-4">Relação Tecnologia - Vaga</h3>
    <h3 class="display-4">@Model.Nome</h3>

    <form id="form" class="mx-auto w-50" asp-controller="Tecnologia" asp-action="AtualizarPeso" method="post">
        @if (Model.Vagas != null && Model.Vagas.Any())
        {
            foreach(var vaga in Model.Vagas)
            {
                <label for="pesoTecs @vaga.Nome">
                    @vaga.Nome
                </label>
                <select class="form-select w-50 mx-auto" name="pesoTecs" id="pesoTecs @vaga.Nome">
                    <option selected> - Selecione uma Opção -</option>
                    <option value="@vaga.Id @Model.Id 2">Baixo</option>
                    <option value="@vaga.Id @Model.Id 5">Médio</option>
                    <option value="@vaga.Id @Model.Id 8">Alto</option>
                </select>
            }
        }
        <div class="d-flex justify-content-around p-3">
            <button type="submit" class="btn btn-primary w-25">Próximo</button>
        </div>
    </form>
    <div class="d-flex justify-content-center">
        <a role="button" class="btn btn-primary" asp-controller="Tecnologia" asp-action="Index"> Voltar Para Listagem </a>
    </div>
</div>

Application_RH/Views/Tecnologia/TecnologiaVagaEditar.cshtml
@model TecnologiaViewModel

@{
    ViewData["Title"] = "Editar - Tecnologia - Vaga";
}

<div class="text-center">
    <h3 class="display-4">Relação Tecnologia - Vaga</h3>
    <h3 class="display-4">Editar "@Model.Nome"</h3>

    <form id="form" class="mx-auto w-50" asp-controller="Tecnologia" asp-action="AtualizarPeso" method="post">
        @if (Model.Vagas != null && Model.Vagas.Any())
        {
            foreach(var vaga in Model.Vagas)
            {
                <label for="pesoTecs @vaga.Nome">
                    @vaga.Nome
                </label>
                <select class="form-select" name="pesoTecs" id="pesoTecs @vaga.Nome">
                    <option selected> - Selecione uma Opção -</option>
                    <option value="@vaga.Id @Model.Id 2">Baixo</option>
                    <option value="@vaga.Id @Model.Id 5">Médio</option>
                    <option value="@vaga.Id @Model.Id 8">Alto</option>
                </select>
            }
        }
        <div class="d-flex justify-content-around p-3">
            <button type="submit" class="btn btn-primary w-25">Próximo</button>
        </div>
    </form>

    <div class="d-flex justify-content-center">
        <a role="button" class="btn btn-primary" asp-controller="Tecnologia" asp-action="Index"> Voltar Para Listagem </a>
    </div>
</div>